[config]
    [source-cluster]
        url = "https://index.elrond.com"
        user = ""
        password = ""
    [destination-cluster]
        url = ""
        user = ""
        password = ""
    [compare]
        num-parallel-reads = 30
        blockchain-start-time = 1596117600 # mainnet start time ( for testnet will be a different start time)
        indices-with-timestamp = ["receipts", "transactions", "blocks", "miniblocks", "rounds",  "accountshistory", "scresults", "accountsesdt", "accountsesdthistory", "scdeploys", "tokens", "accounts", "logs", "operations"]
        indices-no-timestamp = ["rating", "validators", "epochinfo", "tags", "delegators"]
