[config]
    [source-cluster]
        url = "https://index.elrond.com"
        user = ""
        password = ""
    [destination-cluster]
        url = "https://index.elrond.com"
        user = ""
        password = ""
    [compare]
        indices = ["rating", "transactions", "blocks", "validators", "miniblocks", "rounds", "accounts", "accountshistory", "receipts", "scresults", "accountsesdt", "accountsesdthistory", "epochinfo", "scdeploys", "tokens", "tags", "logs", "delegators"]
