[config]
    [source-cluster]
        url = "https://index.elrond.com"
        user = ""
        password = ""
    [destination-cluster]
        url = ""
        user = ""
        password = ""
    [compare]
        interval = [
            {start = 1596117600, stop = 1613397600}, # Day 0 --- Day 200
            {start = 1613397601, stop = 1630677600}, # Day 200 - Day 400
            {start = 1630677601, stop = 1639317601}, # Day 400 - Day 500
            {start = 1639317602, stop = 1647957602}, # Day 500 - Day 600
            {start = 1647957603, stop = 1667288039}, # Day 600 - Day XXX
        ]
        #indices-with-timestamp = [ "receipts", "transactions", "blocks", "miniblocks", "rounds",  "accountshistory", "scresults", "accountsesdt", "accountsesdthistory", "scdeploys", "tokens", "accounts"]
        #indices-with-timestamp = [ "blocks"]
        indices-no-timestamp = ["rating", "validators", "epochinfo", "tags", "logs", "delegators"]
