[config]
    [source-cluster]
        url = "https://index.elrond.com"
        user = ""
        password = ""
    [destination-cluster]
        url = ""
        user = ""
        password = ""
    [compare]
        #indices = ["rating", "transactions", "blocks", "validators", "miniblocks", "rounds", "accounts", "accountshistory", "receipts", "scresults", "accountsesdt", "accountsesdthistory", "epochinfo", "scdeploys", "tokens", "tags", "logs", "delegators"]
        indices-with-timestamp = ["transactions", "blocks", "miniblocks", "rounds",  "accountshistory", "receipts","scresults", "accountsesdt", "accountsesdthistory", "scdeploys", "tokens"]
        indices-no-timestamp = ["rating", "validators", "accounts", "epochinfo", "epochinfo", "tags", "logs", "delegators"]
