global:
  scrape_interval: 6s
  scrape_timeout: 6s
  evaluation_interval: 1m
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 6s
    scrape_timeout: 6s
    metrics_path: /status/prometheus-metrics
    scheme: http
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets:
          - 0.0.0.0:8081
