name: Integration tests

on:
  push:
    branches: [ master, development, feat/* ]
  pull_request:
    branches: [ master, development, feat/* ]

jobs:
  test-1:
    name: Elasticsearch v7.16.2
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17.6
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Run integration tests with Elasticsearch `v7.16.2`
        run: make integration-tests ES_VERSION=7.16.2
  test-2:
    name: Elasticsearch v8.3.2
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15.6
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Run integration tests with Elasticsearch `v8.3.2`
        run: make integration-tests ES_VERSION=8.3.2
  test-3:
    name: OpenSearch v1.2.4
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15.6
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Run integration tests with OpenSearch `v1.2.4`
        run: make integration-tests-open-search OPEN_VERSION=1.2.4

  test-4:
    name: OpenSearch v2.1.0
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15.6
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Run integration tests with OpenSearch `v2.1.0`
        run: make integration-tests-open-search OPEN_VERSION=2.1.0
