name: Integration tests

on:
  push:
    branches: [ master, feat/* ]
  pull_request:
    branches: [ master, feat/* ]

jobs:
  test-1:
    name: Elasticsearch v7.16.2
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15.6
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Run integration tests with Elasticsearch `v7.16.2`
        run: make integration-tests ES_VERSION=7.16.2
  test-2:
    name: Elasticsearch v8.1.1
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15.6
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Run integration tests with Elasticsearch `v8.1.1`
        run: make integration-tests ES_VERSION=8.1.1

  test-3:
    name: Elasticsearch latest
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15.6
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Run integration tests with Elasticsearch `latest`
        run: make integration-tests ES_VERSION=latest
